#! /bin/bash

# Copy the file into /etc/bash_completion.d/ to enable bash command autocomplete
# for bluemix CLI

_bash_autocomplete() {
     local cur prev opts base
     COMPREPLY=()
     cur="${COMP_WORDS[COMP_CWORD]}"
     opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
     COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
     return 0
 }

complete -F _bash_autocomplete bluemix
# bx is the short name of bluemix
complete -F _bash_autocomplete bx
